name: news
description: A new GanzTek application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.3

  #Core
  provider_architecture: ^1.0.6
  logger: ^0.8.3
  # State
  #provider: ^4.0.2
  # Data
  #  json_annotation: ^2.4.0
  dio: ^3.0.8
  rxdart: ^0.22.5
  shared_preferences: ^0.5.6+2
  localstorage: ^3.0.1+4
  sprintf: ^4.0.2
  # UI
  oktoast: ^2.3.1+1
  pull_to_refresh: ^1.5.8
  cached_network_image: ^2.0.0
  flutter_svg: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNext.ttc
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Regular.ttf
  assets:
    - assets/icon/
    - assets/images/
    - assets/demo/
